/********************************************************************
* _pydispatcher.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error _pydispatcher.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable_pydispatcher();
extern void G__cpp_setup_inheritance_pydispatcher();
extern void G__cpp_setup_typetable_pydispatcher();
extern void G__cpp_setup_memvar_pydispatcher();
extern void G__cpp_setup_global_pydispatcher();
extern void G__cpp_setup_memfunc_pydispatcher();
extern void G__cpp_setup_func_pydispatcher();
extern void G__set_cpp_environment_pydispatcher();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "_pydispatcher_processed_event.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G___pydispatcherLN_TClass;
extern G__linked_taginfo G___pydispatcherLN_TBuffer;
extern G__linked_taginfo G___pydispatcherLN_TMemberInspector;
extern G__linked_taginfo G___pydispatcherLN_TObject;
extern G__linked_taginfo G___pydispatcherLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G___pydispatcherLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___pydispatcherLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G___pydispatcherLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G___pydispatcherLN__object;
extern G__linked_taginfo G___pydispatcherLN_TPyDispatcher;
extern G__linked_taginfo G___pydispatcherLN_TPyDispatcherProcessedEvent;

/* STUB derived class for protected member access */
