#!/usr/bin/env python

import sys, os
from optparse import OptionParser

parser = OptionParser()
(options, args) = parser.parse_args()

import ROOT
from rootpy.routines import getTrees

if len(args)<2:
    sys.exit('too few arguments')

if not os.environ.has_key('DATAROOT'):
    print 'Warning: $DATAROOT not defined!'
    dataroot = None
dataroot = os.environ['DATAROOT']

outfile = args[0]
infiles = args[1:]

out = ROOT.TFile.Open(outfile,'recreate')
for infile in infiles:
    out.cd()
    treename = '.'.join(infile.split('.')[:-1]))
    f = ROOT.TFile.Open(infile)
    trees = getTrees(f)
    out.mkdir(treename).cd()
    for tree in trees:
        newTree = tree.CloneTree(-1,'fast')
        newTree.Write()
    f.Close()
out.Close()
