#!/usr/bin/env python
import sys
import os
from optparse import OptionParser
from TauMVA.GridXMLParser import GridXMLParser

parser = OptionParser()
parser.add_option("--dry",
                  action="store_true", dest="dry", default=False,
                  help="do not actually submit jobs or download datasets")
parser.add_option("--onlynew",
                  action="store_true", dest="onlynew", default=False,
                  help="only submit jobs for newly added datasets")
parser.add_option("--get",
                  action="store_true", dest="get", default=False,
                  help="download output datasets")
parser.add_option("--submit",
                  action="store_true", dest="submit", default=False,
                  help="submit jobs")
parser.add_option("--resubmit",
                  action="store_true", dest="resubmit", default=False,
                  help="resubmit jobs")
parser.add_option("--flagged",
                  action="store_true", dest="flagged", default=False,
                  help="submit flagged jobs")
parser.add_option("--uselib",
                  action="store_true", dest="uselib", default=False,
                  help="use a library already on grid and defined in xml file")
parser.add_option("--test",
                  action="store_true", dest="test", default=False,
                  help="submit only test job")
parser.add_option("--site",
                  action="store", type="string", dest="site", default=None,
                  help="override the chosen site in the xml file")
(options, args) = parser.parse_args()

try:
    testarea = os.environ["TestArea"]
except:
    print "Environment variable $TestArea not set!"
    sys.exit(0)
try:
    datadir = os.environ["data"]
except:
    print "Environment variable $data not set!"
    sys.exit(0)

def main():
    
    xml = args[0]
    parser = GridXMLParser(xml,datadir,testarea,options)
    parser.parse()
    
if __name__ == "__main__": main()
