#!/usr/bin/env python

from optparse import OptionParser

parser = OptionParser()
options,args = parser.parse_args()

from rootpy.dataquality import GRL
from operators import add

grls = []
for file in args:
    grls.append(GRL(file))

mergedgrl = reduce(add,grls)
mergedgrl.write("merged_GRL.xml")
