#!/usr/bin/env python

import readline
import cmd
from rootpy.io import open as ropen
import subprocess
from argparse import ArgumentParser
import os
import sys


class shell_cmd(cmd.Cmd, object):

    def do_shell(self, s):

        subprocess.call(s, shell=True)

    def help_shell(self):

        print "execute shell commands"


class empty_cmd(cmd.Cmd, object):
    
    def emptyline(self):

        pass


class exit_cmd(cmd.Cmd, object):

    def can_exit(self):

        return True

    def onecmd(self, line):

        r = super(exit_cmd, self).onecmd(line)
        if r and (self.can_exit() or
           raw_input('exit anyway ? (yes/no):')=='yes'):
             return True
        return False

    def do_exit(self, s):

        return True

    def help_exit(self):

        print "Exit the interpreter."
        print "You can also use the Ctrl-D shortcut."

    do_EOF = do_exit
    help_EOF= help_exit


class roosh(exit_cmd, shell_cmd, empty_cmd):

    def __init__(self, filename):
        
        super(roosh, self).__init__()
        self.file = ropen(filename)
        self.pwd = self.file
        self.prompt = '%s > ' % self.pwd._path
    
    def do_cd(self, path):

        if path == '.':
            return
        self.pwd = self.pwd.GetDirectory(path)
        self.pwd.cd()

    def do_ls(self, s):

        for key in self.pwd.GetListOfKeys():
            print key.GetName()
    
    def postcmd(self, stop, line):
        
        if not stop:
            self.prompt = '%s > ' % self.pwd._path
            return stop
        return stop
        

parser = ArgumentParser()
parser.add_argument('-l', action='store_true', dest='nointro', default=False)
parser.add_argument('file')
args = parser.parse_args()

try:
    terminal = roosh(args.file)
    if args.nointro:
        terminal.cmdloop()
    else:
        terminal.cmdloop("Welcome to the ROOSH terminal")
except Exception, e:
    sys.exit(e)
