#!/usr/bin/env python

# This script converts all TTrees in a ROOT file into HDF5 format.

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('files', nargs='+')
args = parser.parse_args()

import sys
import os
import traceback
import tables
from rootpy.io import open as ropen
from rootpy.root2tables import convert 

for inputname in args.files:
    outputname = os.path.splitext(inputname)[0] + '.h5'
    try:
        rootfile = ropen(inputname)
    except:
        sys.exit("Could not open %s" % inputname)
    try:
        filters = tables.Filters(complib='blosc', complevel=5)
        hd5file = tables.openFile(filename=outputname, mode='w', title='Data',
                                  filters=filters)
    except IOError:
        sys.exit("Could not create %s" % outputname)
    try:
        print "Converting %s ..." % inputname
        convert(rootfile, hd5file, stream=sys.stdout)
        print "Created %s" % outputname
    except KeyboardInterrupt:
        print
        print "Caught Ctrl-c ... cleaning up"
        os.unlink(outputname)
        break
    finally:
        hd5file.close()
        rootfile.Close()
