#!/usr/bin/env python

from rootpy import io
import ROOT
import sys

textfile = sys.argv[1]
rootfile = sys.argv[2]

rootfile = io.open(rootfile,"update")
textfile = open(textfile)
text = textfile.read()

named = ROOT.TNamed("TreeInfo","")
named.SetTitle(text)
named.Write("",ROOT.TObject.kOverwrite)
