#!/usr/bin/env python
from optparse import OptionParser

parser = OptionParser()
options,args = parser.parse_args()

import sys, os
from ROOT import TFile, gDirectory
from ROOTPy.routines import *

def recursive_ls(path="",depth=0):
    prefix = '   '*depth
    dir = gDirectory.GetDirectory(path)
    if not dir:
        print "unable to traverse into directory %s"%dir
        return
    objects = getObjects(dir)
    for thing in objects:
        if isinstance(thing,ROOT.TDirectory):
            print prefix+thing.GetName()
            recursive_ls("/".join([path,thing.GetName()]),depth+1)
        else:
            output = "%s %s"%(prefix+thing.__class__.__name__,thing.GetName())
            if hasattr(thing,"GetEntries"):
                output += " Entries: %i"%thing.GetEntries()
            if hasattr(thing,"GetWeight"):
                output += " Weight: %e"%thing.GetWeight()
            if hasattr(thing,"Integral"):
                output += " Integral: %e"%thing.Integral()
            print output
            
for filename in args:
    if not os.path.isfile(filename):
        print "file %s does not exist"%filename
        sys.exit(1)
    file = TFile.Open(filename)
    if not file:
        print "could not open file %s"%filename
    recursive_ls("")

