#!/usr/bin/env python

from optparse import OptionParser
import sys
import os
import re

parser = OptionParser()
options,args = parser.parse_args()

import ROOT
from ROOT import TFile
from rootpy.routines import getTrees
from rootpy.regex import VALIDPATH

validpath = re.compile(VALIDPATH)

target = args[-1]
sources = args[:-1]

match = re.match(validpath,target)
if match:
    targetfilename = match.group('file')
    targetpathname = match.group('path')
else:
    sys.exit("target file %s is not a valid path"% target)

targetFile = TFile.Open(targetfilename,'update')
if not targetFile:
    sys.exit("cannot open target file %s"% targetfilename)

targetpath = os.path.dirname(targetpathname)
treename = os.path.basename(targetpathname)

if len(sources) > 1 and :
    sys.exit('Multiple sources specified while specifying target tree name')

for source in sources:
    filename,treename = source.split(':')
    f = TFile.Open(filename)
    if not f:
        sys.exit("file %s will not open"%filename)
    if not treename:
        trees = getTrees(f)
    else:
        trees = [f.Get(treename)]
    for tree in trees:
        if tree:
            targetFile.cd()
            newTree = tree.CloneTree(-1,'fast')
            if targetTreename:
                targetName = targetTreename
            else:
                targetName = treename
            newTree.SetName(targetName)
            newTree.Write('',ROOT.TObject.kOverwrite)
        else:
            f.Close()
            sys.exit("%s not found in %s"%(treename,filename))
    f.Close()
targetFile.Close()
