#!/usr/bin/env python

import ROOT
import sys

files = []
if len(sys.argv) > 1:
    for f in sys.argv[1:]:
        files.append(ROOT.TFile.Open(f))

browser = ROOT.TBrowser()
raw_input("Press ENTER to exit")

for f in files:
    f.Close()
