#!/usr/bin/env python

from optparse import OptionParser

parser = OptionParser()
parser.add_option("-t","--tree", action="store", type="str", dest="tree",
                  help="Tree name", default=None)
parser.add_option("-o","--output", action="store", type="str", dest="output",
                  help="Output file name", default=None)
options, args = parser.parse_args()

from ROOT import TChain

chain = TChain(options.tree)
for filename in args:
    chain.Add(filename)

chain.Merge(options.output)
