#! /bin/env python

import rootpy
from rootpy.extern import argparse
from rootpy.userdata import BINARY_PATH
import os

parser = argparse.ArgumentParser(description='add one or multiple include paths to be used when compiling JIT dictionaries')
parser.add_argument('paths', nargs='+', help='include paths, absolute')
args = parser.parse_args()

if not os.path.exists(BINARY_PATH):
   os.makedirs(BINARY_PATH)

include_list = os.path.join(
   BINARY_PATH,
   'include_paths.list'
)

with open(include_list, 'a') as inc_list:
   for path in args.paths:
      inc_list.write(path)
      inc_list.write('\n')
