#!/usr/bin/env python
# Copyright 2012 the rootpy developers
# distributed under the terms of the GNU General Public License

# This script converts all TTrees in a ROOT file into HDF5 format.

from rootpy.extern.argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('-n', '--entries', type=int, default=-1,
        help="number of entries to read at once (read all entries by default)")
parser.add_argument('files', nargs='+')
args = parser.parse_args()

import sys
import os
import traceback
import tables
from rootpy.io import open as ropen
from rootpy.root2tables import convert 
import rootpy
rootpy.log.basic_config_colorized()
from rootpy import log; log = log[os.path.basename(__file__)]

for inputname in args.files:
    outputname = os.path.splitext(inputname)[0] + '.h5'
    try:
        rootfile = ropen(inputname)
    except:
        sys.exit("Could not open %s" % inputname)
    try:
        filters = tables.Filters(complib='blosc', complevel=5)
        hd5file = tables.openFile(filename=outputname, mode='w', title='Data',
                                  filters=filters)
    except IOError:
        sys.exit("Could not create %s" % outputname)
    try:
        log.info("Converting %s ..." % inputname)
        convert(rootfile, hd5file, entries=args.entries)
        log.info("Created %s" % outputname)
    except KeyboardInterrupt:
        log.info("Caught Ctrl-c ... cleaning up")
        os.unlink(outputname)
        break
    finally:
        hd5file.close()
        rootfile.Close()
