#!/usr/bin/env python

import readline
from cmd import Cmd
from rootpy.io import open as ropen

class Roosh(Cmd):
    
    def precmd(self, line):
        
        print line

terminal = Roosh()
terminal.prompt = '> '
terminal.cmdloop("Welcome to the ROOSH terminal")
