#!/usr/bin/env python

import pkg_resources
import shutil
import stat
import sys
import os

filename = sys.argv[1]
if not os.path.exists(filename):
    print "Copying %s from rootpy..." % filename
    setup_script = pkg_resources.resource_filename('rootpy', 'etc/%s' % filename)
    try:
        shutil.copyfile(setup_script, filename)
        os.chmod(filename, stat.S_IRUSR | stat.S_IWUSR | stat.S_IXUSR |\
                           stat.S_IRGRP | stat.S_IROTH)
    except IOError, e:
        sys.exit(e)
