#!/usr/bin/env python

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('-t', '--tree')
parser.add_argument('-n', '--entries', type=int, default=1)
parser.add_argument('infile')
parser.add_argument('outfile')
args = parser.parse_args()

from rootpy.io import open
from rootpy.tree import Tree

with open(args.infile, 'read') as inf:
    intree = inf.Get(args.tree)
    with open(args.outfile, 'recreate') as outf:
        outtree = Tree()
        outtree.set_buffer(intree.buffer, create_branches=True)
        for entry in xrange(args.entries):
            intree.GetEntry(entry)
            outtree.Fill()
        outtree.Write()
